# Generated by Django 4.1 on 2022-09-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.AddField(
            model_name='author',
            name='author_id',
            field=models.PositiveBigIntegerField(default=100000, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='author',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.PositiveIntegerField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
