# Generated by Django 4.1 on 2022-09-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_publisher_author_initials_book_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'publisher']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='publisher_id',
        ),
        migrations.AddField(
            model_name='author',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='author_headshots'),
        ),
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='salutation',
            field=models.CharField(blank=True, choices=[('MR', 'Master'), ('MS', 'Miss'), ('PROF', 'Professor'), ('REV', 'Reverand'), ('DR', 'Doctor')], default='MR', help_text='Your prefered title for salutation', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='bookshot',
            field=models.ImageField(blank=True, null=True, upload_to='book_bookshots'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
