# Generated by Django 4.1 on 2022-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blogs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='Summary', max_length=1000),
        ),
    ]
